theme: jekyll-theme-minimal

title: Do Major Film Studios Benefit from a "Halo Effect"?

description: An analysis of audience–critic rating gaps between major and non-major films

show_downloads: false
